### ISSUE TITLE
Import existing project to the editor

### ISSUE THREAD

**Issue by fenos** [slothking-online/graphql-editor#12]
Hi! Amazing project, well done.

Is there a possibility to import existing GraphQL project and its schema to the `graphql-editor`?

If not - it will be great to provide a functionality which we can point a `schema.json` or a `graphql endpoint url` to the editor so that it can use introspection to draw an automatic graph (when using this feature it might be disabling automatic code generation?)

Thanks again!

**Comment by aexol** [comment]
Putting this on roadmap!

**Comment by aexol** [comment]
Hello again. You can import your schema now. It lacks customs scalars for now, but stay tuned!

**Comment by aexol** [comment]
@fenos
