### ISSUE TITLE
Add ability to use interface as type argument

### ISSUE THREAD

**Issue by eljenso** [slothking-online/graphql-editor#15]
GraphQL supports the following:
```
interface IElement {
  children(id: ID): [IElement]
}
```
But I can't find a way to make a graph which produces this.

**Comment by aexol** [comment]
I am a little bit confused. What should be returned from children then? Array of original type which implements the interface ?

**Comment by eljenso** [comment]
Consider the following zoo example (please ignore the uselessness of this interface):
```
inteface IAnimal {
  name: String
}

type Lion implements IAnimal {
  name: String
}
type Elephant implements IAnimal {
  name: String
}

type Zoo {
  animals: [IAnimal]
}
```

The `animals` array of `Zoo` can have any combination of elements of types implementing `IAnimal`.  
If you later implement a new animal like monkey as `type Monkey implements IAnimal`, then this new type is also valid as member of `Zoo`.

See: https://graphql.org/learn/schema/#interfaces

**Comment by aexol** [comment]
Ok, now I understand. Will implement soon

**Comment by aexol** [comment]
done in last commit !
