### ISSUE TITLE
Pivot to a query creation?

### ISSUE THREAD

**Issue by nodkz** [slothking-online/graphql-editor#32]
I tried this tool and it's not a comfortable way for schema creation. You need to use mouse and keyboard. 

I think that you may do a pivot and use it for QUERY creation. And it will be a really cool and comfortable tool. It's really to create the query only by mouse.

**Comment by aexol** [comment]
Thanks for the suggestion! We will generate frontend libs in future where you will get typesafe autocompleted queries for your schema, sounds ok?

**Comment by aexol** [comment]
@nodkz we will create another github repo for that. The idea is to  have diagram where you click on basice query/mutation/subscription nodes. So you generate query by selecting nodes
