### ISSUE TITLE
Add icons to nodes

### ISSUE THREAD

**Issue by robmatyszewski** [slothking-online/graphql-editor#50]

**Comment by konsvasi** [comment]
Can I get a description of what exactly you are looking for?

**Comment by aexol** [comment]
Hi Kostas these issue is rather related to 
https://github.com/slothking-online/diagram
this repo. To add icons means we can replace text inside node with icon

**Comment by robmatyszewski** [comment]
Yeah, we are aiming that the tool will be more easy to use by non-tech people. This idea came from one of our users. We want to have auto-added icons for most popular nodes (words) or selected form database.

**Comment by aexol** [comment]
this is the diagram issue
