### ISSUE TITLE
Load not working

### ISSUE THREAD

**Issue by cwcoffman** [slothking-online/graphql-editor#52]
Just tried to reload a model I had created this morning and... won't load.  You can select the file, and it throws no errors, but the model just doesn't show up.  I really love this editor and hope I'm just missing something!

I really appreciate you putting this software together.  Even now when I can't load, I'm using it as a visual editor and for testing.  Thanks for sharing with the community.

MacOS Mojave - tried Firefox and Safari

**Comment by aexol** [comment]
Hi I've just received your files. Looks like they lack queries. However I will repair that in the ediotr you shouldnt be allowed to save invalid files. Thank you! I will fix your files for you today and send them back.

**Comment by cwcoffman** [comment]
Awesome!! Now that I know I just need queries, that’s great.   Thank you!

Chad Coffman
(720) 352-4463

________________________________

**Comment by aexol** [comment]
I ‘repaired’ your schema. You had references to types which dont exist  and commented in the wrong format. However you help me found issue that editor doesn't support empty types, now it does!

Artur Czemiel, Aexol
ul.Mławska 4 lok 7U
Białystok, Poland
aexol@aexol.com
www.aexol.com

**Comment by cwcoffman** [comment]
Artur,

Dziękuje za pomoc! Bardzo podoba mi się narzędzie, które stworzyłeś, a my przyjmiemy go do edycji / przeglądania schematów GraphQL w Blast Motion. Dziękuję za kontynuację nad tym i za pomoc w ten weekend!

**Comment by cwcoffman** [comment]
Last question - you didn't include the changes you made - would you be willing to do so?  I'm curious if it was the empty types, the lack of queries - or both?  I just want to make sure I follow the conventions.

Thanks!

**Comment by aexol** [comment]
In your file, there were references to types that didn’t exist, comments were in the bad format and there was no main query. You need to have at least one query type.
Artur Czemiel, Aexol
ul.Mławska 4 lok 7U
Białystok, Poland
aexol@aexol.com
www.aexol.com

**Comment by cwcoffman** [comment]
Thank you!
