### ISSUE TITLE
Demo "Press and hold spacebar to add new nodes" not allowing me to move mouse to choices

### ISSUE THREAD

**Issue by farmanp** [slothking-online/graphql-editor#55]
I pulled the most recent changes to my local environment and checked the deployed demo - when I hold spacebar, my mouse is unable to move to the choices that come up. I am using a Spectre x360 on a Windows 10 in Google Chrome. Please advise.

**Comment by aexol** [comment]
cursor is not updating or disappearing at all?

**Comment by duesee** [comment]
I had the same problem. This seems to be a feature of your desktop environment. Something like "disable touchpad when typing". I was able to disable that on my linux machine with the gnome tweak tool (in case some linux user is reading here). Maybe this gives you a direction where to look.

**Comment by aexol** [comment]
Thank you all. We will be dropping spacebar menu or leave it as an option. Spacebar menu lead us to implement our own cursors because Firefox is not capable of handling it with normal cursor. New context menu will accept right mouse button as input. Sounds ok? Let me know please

**Comment by duesee** [comment]
I was just playing around, so not sure how valuable my opinion is here :-) But holding a key doesn't felt right for me. If more people have the same feeling **and** it causes technical problems, then dropping it sounds good.

PS: Blender also uses the spacebar to open menues, but they stay open after a single click.

**Comment by aexol** [comment]
Does RMB sounds good to you @duesee ?

**Comment by duesee** [comment]
RMB?

**Comment by aexol** [comment]
Right mouse button :)

**Comment by duesee** [comment]
Hehe, oh :-) Yes, sounds good :-)

**Comment by FinnFrotscher** [comment]
+1
