### ISSUE TITLE
Integration with Airtable (read desc)

### ISSUE THREAD

**Issue by robmatyszewski** [slothking-online/graphql-editor#74]
1. Increasing demand for now code solutions - check this link - airbnb clone build with airtable https://twitter.com/bentossell/status/1093921136419713026 (238 likes, 5000 views).
2. Airtable is the biggest player in no code https://www.g2crowd.com/categories/no-code-development-platforms
3. Huge demand for GraphQL Endpoint in Airtable. https://community.airtable.com/t/api-idea-graphql-endpoint/3639

**Comment by aexol** [comment]
Impossible to do - we checked it out with @Dennor we need to seek for another candidate. Any ideas?
Syncano, Architect etc. or other direction

**Comment by aexol** [comment]
@maciejkorsan Are you interested in writing syncano integration ?
